ignore:
  - "Com.Danliris.Service.Finance.Accounting.Lib/AutoMapperProfiles"
  - "Com.Danliris.Service.Finance.Accounting.Lib/Migrations"
  - "Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/BudgetCashflow"
  - "Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDispositionExpedition"
  - "Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDispositionPaymentReport"
  - "Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDownPaymentReport"
  - "Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentPurchasingPphBankExpenditureNote"
  - "Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDebtBalance/Excel"
  - "Com.Danliris.Service.Finance.Accounting.Lib/BusinessLogic/GarmentDebtBalance/Pdf"
  - "Com.Danliris.Service.Finance.Accounting.Lib/ViewModels/MemoGarmentPurchasing"
  - "Com.Danliris.Service.Finance.Accounting.Lib/Helpers"
  - "Com.Danliris.Service.Finance.Accounting.Lib/Enums"
  - "Com.Danliris.Service.Finance.Accounting.WebApi/Program.cs"
  - "Com.Danliris.Service.Finance.Accounting.WebApi/Tools"
  - "Com.Danliris.Service.Finance.Accounting.WebApi/Startup.cs"